name: Python Agent CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      run: uv sync

    - name: Check formatting with ruff
      run: uvx ruff format --check .

    - name: Lint with ruff
      run: uvx ruff check .

    - name: Test with pytest
      run: uv run pytest